${#include "nav.h"}$
${#include <time.h>}$

${static const char *page_title = NULL;}$
${static const char *page_description = "Ruan's personal website - under construction...";}$
${static const char *head_extra = NULL;}$

${void header(void) {}$
${if (!page_title) {
    nob_log(INFO, "Set page title with $""{page_title = \"...\";}""$");
}}$
$[toggle_ignore]$
<!DOCTYPE html>
<html lang="en-ZA">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="$(page_description)$">
    <title>$(page_title ? "%s – " : "", page_title)$Pysoft</title>
    <link rel="stylesheet" href="/site.css">
    $(head_extra ? head_extra : "")$
</head>
<body>
    <header id="header">
        <nav id="navbar">
        ${for (size_t i = 0; i < nav_links_count; ++i) {}$
            ${const NavLink link = nav_links[i];}$
            <a href="$(link.href)$" ${if (link.id) {}$ id="$(link.id)$" ${}}$>$(link.name)$</a>
        ${}}$
        </nav>
    </header>
    <main>
$[toggle_ignore]$
${}}$

${static const char *license_extra = NULL;}$

${void footer(void) {}$
$[toggle_ignore]$
    </main>
    <footer id="footer">
        <p>&copy; 2023&mdash;2026 <a href="https://pysoft.co.za">Ruan</a></p>
        <p>Some css from <a href="https://hastysite.h3rald.com">HastySite</a></p>
        <p>
            Website content licensed under the 
            <a href="https://creativecommons.org/licenses/by/4.0/">
                Creative Commons Attribution 4.0 International
            </a>
            license, unless otherwise specified.
        </p>
        <p>Website generated by <a href="https://github.com/Ruan-pysoft/webgen">my custom C-based SSG</a></p>
        <p>Website source available <a href="https://github.com/Ruan-pysoft/pysoft">here</a></p>
        $(license_extra ? license_extra : "")$
    </footer>
</body>
</html>
$[toggle_ignore]$
${}}$

${const char *asset(const char *name) {
    return temp_sprintf("/assets/%s", name);
}}$
${const char *image(const char *name) {
    return asset(temp_sprintf("/images/%s", name));
}}$

${void makeLinkTo(const char *name, const char *path) {
    fprintf(OUTFILE, "<a href=\"%s\">%s</a>", path, name);
}}$

${void makeLink(const char *path) {
    makeLinkTo(path, path);
}}$

${
struct {
    const char **items;
    size_t count;
    size_t capacity;
} footnotes = {0};

void fn(void) {
    nob_da_append(&footnotes, NULL);

    const size_t fn_num = footnotes.count;
    fprintf(OUTFILE, "<sup><a href=\"#fn%lu\" id=\"fnref%lu\" class=\"footnote-ref\">%lu</a></sup>", fn_num, fn_num, fn_num);
}
void fn_text(const char *text) {
    size_t idx = 0;
    for (; idx < footnotes.count; ++idx) {
        if (footnotes.items[idx] == NULL) break;
    }
    if (idx == footnotes.count) {
        nob_log(ERROR, "Cannot create footnote text without footnote reference first!");
       return;
    }
    footnotes.items[idx] = text;
    const size_t fn_num = idx+1;
    fprintf(OUTFILE, "<div class=\"footnote\" id=\"fn%lu\"><sup><a href=\"#fnref%lu\" class=\"footnote-backref\">^%lu</a></sup> %s</div>", fn_num, fn_num, fn_num, text);
}
}$

${
#define is_digit(ch) ('0' <= (ch) && (ch) <= '9')
bool date_validate(const char *date) {
    // date must be in YYYY-mm-DD format
    if (
        !is_digit(date[0]) || !is_digit(date[1]) || !is_digit(date[2]) || !is_digit(date[3])
        || date[4] != '-'
        || !is_digit(date[5]) || !is_digit(date[6])
        || date[7] != '-'
        || !is_digit(date[8]) || !is_digit(date[9])
    ) {
        nob_log(ERROR, "Date '%s' is not in YYYY-mm-DD format!", date);
        return false;
    }
    return true;
}
int get_day_from_date(const char *date) {
    if (!date_validate(date)) return 1;
    const int day = (date[8]-'0')*10 + (date[9]-'0');
    if (day == 0 || day > 31) {
        nob_log(ERROR, "In date '%s', day should be in the range 1-31 (inclusive)!", date);
        return 1;
    }
    return day;
}
int get_month_from_date(const char *date) {
    if (!date_validate(date)) return 1;
    const int month = (date[5]-'0')*10 + (date[6]-'0');
    if (month == 0 || month > 12) {
        nob_log(ERROR, "In date '%s', month should be in the range 1-12 (inclusive)!", date);
        return 1;
    }
    return month;
}
int get_year_from_date(const char *date) {
    if (!date_validate(date)) return 1;
    const int year = (date[0]-'0')*1000 + (date[1]-'0')*100 + (date[2]-'0')*10 + (date[3]-'0');
    return year;
}
}$
